name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 # v1.195.0
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
